# -*- coding: utf-8 -*-
"""BotMensa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10b7JVrYu-78kMgDWu9Upyt268REMs16Q

# Requirements
"""

import requests
from bs4 import BeautifulSoup
import tabula
#from tabula import read_pdf
from IPython.display import display, HTML
import telebot












## Get PDF

"""# Get Pdf"""

#get url
  
URL = "https://www.dsu.toscana.it/i-menu"
r = requests.get(URL)

#encode it nicely
soup = BeautifulSoup(r.content, 'html5lib') # If this line causes an error, run 'pip install html5lib' or install html5lib
#print(soup.prettify()) #to see html code of selected page

#fammi una lista di tutti i paragrafi
paragraphs=soup.find_all('p')



def get_pdf_link(nome_mensa):
    #scorrimi i paragragrafi
    for paragraph in paragraphs:
        if nome_mensa in paragraph.text: #quando trovi il nome della mensa salvami solo quel paragrafo
            links = paragraph.find_all("a") #dammi tutti i link nel paragrafo di quella mensa
    pdf_link = 'https://www.dsu.toscana.it'+links[0].get('href') + ".pdf" #encode it in a string
    return pdf_link


def get_pdf_link_prati_pranzo(nome_mensa):
    #scorrimi i paragragrafi
    for paragraph in paragraphs:
        if nome_mensa in paragraph.text: #quando trovi il nome della mensa salvami solo quel paragrafo
            links = paragraph.find_all("a") #dammi tutti i link nel paragrafo di quella mensa
    pdf_link = 'https://www.dsu.toscana.it'+links[0].get('href') + ".pdf" #encode it in a string
    return pdf_link

def get_pdf_link_prati_cena(nome_mensa):
    #scorrimi i paragragrafi
    for paragraph in paragraphs:
        if nome_mensa in paragraph.text: #quando trovi il nome della mensa salvami solo quel paragrafo
            links = paragraph.find_all("a") #dammi tutti i link nel paragrafo di quella mensa
    pdf_link = 'https://www.dsu.toscana.it'+links[1].get('href') + ".pdf" #encode it in a string
    return pdf_link

"""# Menu in pdf"""

name_of_mensa='Martiri'
pdf_link=get_pdf_link(name_of_mensa)

box=[170,20,500,840]
tl = tabula.read_pdf(pdf_link, pages='1',area=box,output_format="dataframe", guess=False,pandas_options={'header':None},stream=False)
df = tl[0]
df = df.replace(r'\r',' ', regex=True)
# Assuming the variable df contains the relevant DataFrame
#df=df.dropna(axis=1)

col_names=['Lunedì','Martedì','Mercoledì','Giovedì','Venerdì','Sabato','Domenica']

df=df.set_axis(col_names,axis=1)

df=df.iloc[1:]

display(df.style.set_properties(**{
    'text-align': 'left',
    'white-space': 'pre-wrap',
}))

def pretty_print(df):
    return display( HTML( df.to_html().replace("\\r","<br>") ) )

#pretty_print(df)

#display(df.style.set_properties(**{
#    'text-align': 'left',
#    'white-space': 'pre-wrap',
#}))

#table = tabula.read_pdf(pdf_link,pages=1)






'''


"""# Bot telegram"""
from telebot import types

bot = telebot.TeleBot("5081479799:AAFoUjqhKlJmoLowkubtZHcjYw_jhx1zHEg")

TOKEN = '5081479799:AAFoUjqhKlJmoLowkubtZHcjYw_jhx1zHEg'
tb = telebot.TeleBot(TOKEN)

user = tb.get_me()

@bot.message_handler(commands=['start'])
def send_welcome(message):
    bot.reply_to(message, "Prego per lei? \nBenvenuto nel nuovo Bot delle Mense DSU!")

@bot.message_handler(commands=['help'])
def send_help(message):
    bot.reply_to(message, "Segnala bug a @avodroc_oiluig")

@bot.message_handler(commands=['setup'])
def setup(message):
    markup=types.ReplyKeyboardMarkup(row_width=2)
    itembtn1 = types.KeyboardButton('Martiri')
    itembtn2 = types.KeyboardButton('Praticelli')
    itembtn3 = types.KeyboardButton('Betti')
    markup.add(itembtn1, itembtn2, itembtn3)
    bot.reply_to(message, "Qual è la tua mensa preferita?", reply_markup=markup)

@bot.callback_query_handler(lambda query: query.data == "Martiri")
def process_callback_1(query):
  #global mensa_name
  #mensa_name='Martiri'
  markup = types.ReplyKeyboardRemove(selective=True)
  bot.reply_to(message, "Risposta registrata, grazie!", reply_markup=markup)

#print(mensa_name)

@bot.message_handler(commands=['pranzo'])
def menu_pranzo(message):


bot.infinity_polling()
'''
